author: STUIX # 作者
description: Student & Technology United Internet Exchanges
keyword: 
favicon:

excerpt_link: Read more

menu:
 Home: /
 #Tags: /tags/
 Archives: /archives/
 #Projects: /project/
 #About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment, uyan or disqus

comment: false 

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id:
google_analytics:
# disqus config
disqus_shortname:

about:
  banner: http://file.muyutech.com/about.jpg
  avatar: https://avatars3.githubusercontent.com/u/16443628?v=3&s=460
  description: "The end is always near."
  weibo_username:
  twitter_username:
  github_username: STU-IX
  zhihu_username:
  douban_username:
  linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
